// ch10/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "./hello-world.js";
  import "./radio-group.js";

  const initialColor = "red";
  let helloWorldElement: HTMLElement | undefined = undefined;
  let radioGroupElement: HTMLElement | undefined = undefined;

  onMount(() => {
    const color = radioGroupElement
      ? (radioGroupElement as any).value
      : "black";
    updateColor(color);
  });

  function handleChange(event: CustomEvent) {
    updateColor(event.detail.value);
  }

  function updateColor(color: string) {
    if (helloWorldElement) (helloWorldElement as any).color = color;
  }
</script>

<main>
  <hello-world name="Mark" bind:this={helloWorldElement}></hello-world>
  <radio-group
    name="color"
    bind:this={radioGroupElement}
    labels="Red,Green,Blue"
    value={initialColor}
    values="red,green,blue"
    onchange={handleChange}
  ></radio-group>
</main>

// ch10/angular/src/app/app.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, viewChild } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import "./hello-world.js";
import "./radio-group.js";

@Component({
  selector: "app-root",
  imports: [RouterOutlet],
  templateUrl: "./app.html",
  styleUrl: "./app.css",
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class App {
  readonly initialColor = "red";
  private helloWorldRef = viewChild<ElementRef>("helloWorldTag");

  ngAfterViewInit(): void {
    this.updateColor(this.initialColor);
  }

  handleChange(event: Event) {
    const color = (event as CustomEvent).detail.value;
    this.updateColor(color);
  }

  updateColor(color: string) {
    const el = this.helloWorldRef();
    if (el) (el.nativeElement as any).color = color;
  }
}
